from __future__ import annotations

import pytest


# Minimal valid agent_defaults.yaml for test workspaces
_AGENT_DEFAULTS = """\
version: 1
agents:
  - id: worker_default
    role: worker
    provider: codex
    model: gpt-5.3-codex
    tools_allow: [tool:*]
  - id: orchestrator_default
    role: orchestrator
    provider: codex
    model: gpt-5.3-codex
behaviors:
  - id: prepare_dispatch_default
    kind: prepare_dispatch
    agent: orchestrator_default
    enabled: true
  - id: merge_default
    kind: merge_and_conflict_resolution
    agent: orchestrator_default
    enabled: true
  - id: summarize_default
    kind: summarize_work
    agent: orchestrator_default
    enabled: true
"""


@pytest.fixture(autouse=True)
def _enable_simulated_backend(monkeypatch: pytest.MonkeyPatch, tmp_path) -> None:  # type: ignore[no-untyped-def]
    monkeypatch.setenv("RALPHITE_DEV_SIMULATED_EXECUTION", "1")

    # Write a valid agent_defaults.yaml into every test's tmp_path so that any
    # plan generated by goal_to_plan (which embeds agent_defaults_ref) passes validation.
    (tmp_path / "agent_defaults.yaml").write_text(_AGENT_DEFAULTS, encoding="utf-8")

    from ralphite.engine import LocalOrchestrator

    monkeypatch.setattr(LocalOrchestrator, "require_git_workspace", lambda self: None)
    monkeypatch.setattr(
        LocalOrchestrator,
        "git_runtime_status",
        lambda self: {"ok": True, "detail": "test-ok"},
    )
