from __future__ import annotations

RECOVER_EXIT_SUCCESS = 0
RECOVER_EXIT_NO_RECOVERABLE = 10
RECOVER_EXIT_UNRECOVERABLE = 11
RECOVER_EXIT_INVALID_INPUT = 12
RECOVER_EXIT_PREFLIGHT_FAILED = 13
RECOVER_EXIT_PENDING = 14
RECOVER_EXIT_TERMINAL_FAILURE = 15
RECOVER_EXIT_INTERNAL_ERROR = 16
